# k8s-resources.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mac-rwx-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mac-hostpath
  hostPath:
    path: /mnt/disk-volume1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rwx-pvc-myfiopod1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: mac-hostpath
---
apiVersion: v1
kind: Pod
metadata:
  name: myfiopod1
  namespace: default
spec:
  containers:
  - name: fio
    image: fio-alpine
    imagePullPolicy: IfNotPresent
    command: ["sleep"]
    args: ["infinity"]
    volumeMounts:
    - name: rwx-volume
      mountPath: /mnt/disk-volume1
  volumes:
  - name: rwx-volume
    persistentVolumeClaim:
      claimName: rwx-pvc-myfiopod1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myfiopod
  namespace: default
spec:
  serviceName: myfiopod
  replicas: 33
  selector:
    matchLabels:
      app: fio
  template:
    metadata:
      labels:
        app: fio
    spec:
      containers:
        - name: fio
          image: fio-alpine
          imagePullPolicy: IfNotPresent
          command: ["sleep"]
          args: ["infinity"]
          volumeMounts:
            - name: rwx-volume
              mountPath: /mnt/disk-volume1
      volumes:
        - name: rwx-volume
          persistentVolumeClaim:
            claimName: rwx-pvc-myfiopod1
